# Задача 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [1]:
import numpy as np

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй — числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец — это признак, а строка — наблюдение.

In [2]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 

In [5]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp

8.0

Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [6]:
watched = len(a) - 1
cov = a_centered_sp / watched
cov

2.0

Проверьте получившееся число, вычислив ковариацию с помощью функции np.cov

In [7]:
check_cov = np.cov(a.transpose())[0, 1]
cov == check_cov

True

# Задача 2
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.

In [8]:
import pandas as pd

Создайте датафрейм authors со столбцами author_id и author_name,
в которых соответственно содержатся данные: 
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [9]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3], 
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

Создайте датафрейм book cо столбцами author_id, book_title и price,
в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [10]:
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3], 
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [11]:
authors_price = authors.merge(book, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [12]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,
минимальная, максимальная и средняя цена на книги этого автора.

In [13]:
authors_stat = top5.groupby('author_name', as_index=False).agg({'price': {
    'min_price': 'min', 
    'max_price': 'max', 
    'mean_price': 'mean'
}})
authors_stat.columns = [x[1] if x[1] else x[0] for x in authors_stat.columns.ravel()]
authors_stat

/Users/a.iatsuk/.conda/envs/geekbrains/lib/python3.7/site-packages/pandas/core/groupby/generic.py:1315: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)


author_name  min_price  max_price  mean_price
0  Островский        370        370         370
1    Тургенев        350        450         400
2       Чехов        450        500         475

Создайте новый столбец в датафрейме authors_price под названием cover, 
в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. 
В этот столбец поместите данные из следующего списка: 
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [14]:
authors_price['cover'] = pd.Series(['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'])
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

In [15]:
? pd.pivot_table

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.
Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая»,
а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, 
при необходимости загрузите библиотеку Numpy. Назовите полученный датасет book_info.

In [16]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc='sum', fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

Сохраните полученный датасет book_info в формат pickle под названием "book_info.pkl".
Затем загрузите из этого файла датафрейм и назовите его book_info2.
Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [17]:
book_info.to_pickle('book_info.pkl')

In [18]:
book_info2 = pd.read_pickle('book_info.pkl')

In [19]:
book_info.equals(book_info2)


True