# Линейная алгебра
## Урок 2. Матрицы и матричные операции

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием NumPy.

In [1]:
import numpy as np

### Часть 1

#### Задача 1
Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
1. $A$ – матрица $4\times2$, $B$ – матрица $4\times2$;
2. $A$ – матрица $2\times5$, $B$ – матрица $5\times3$;
3. $A$ – матрица $8\times3$, $B$ – матрица $3\times8$;
4. $A$ – квадратная матрица $4\times4$, $B$ – квадратная матрица $4\times4$.
##### Решение

1. $AB$ – нельзя умножать, $BA$ – нельзя умножать
2. $AB$ – $2\times3$, $BA$ – нельзя умножать
3. $AB$ – $8\times8$, $BA$ – $3\times3$
4. $AB$ – $4\times4$, $BA$ – $4\times4$

In [4]:
print('2. AB =', np.dot(np.ones((2,5)), np.ones((5,3))).shape)
print('3. AB =', np.dot(np.ones((8,3)), np.ones((3,8))).shape)
print('3. BA =', np.dot(np.ones((3,8)), np.ones((8,3))).shape)
print('4. AB = BA =', np.dot(np.ones((4,4)), np.ones((4,4))).shape)

2. AB = (2, 3)
3. AB = (8, 8)
3. BA = (3, 3)
4. AB = BA = (4, 4)


#### Задача 2 
Найти сумму и произведение матриц $A = \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix}$ и $B = \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix}$.
##### Решение

$$A + B = B + A = \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix} + \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\ 
3 & 5 
\end{pmatrix}$$

$$AB = \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
1\cdot4-2\cdot0 & 1\cdot(-1)-2\cdot5 \\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5 
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\ 
12 & -3 
\end{pmatrix}$$

$$BA = \begin{pmatrix}
4 & -1 \\ 
0 & 5 
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2 \\ 
3 & 0 
\end{pmatrix} = \begin{pmatrix}
4\cdot1-1\cdot3 & 4\cdot(-2)-1\cdot0 \\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0 
\end{pmatrix} = \begin{pmatrix}
1 & -8 \\ 
15 & 0 
\end{pmatrix}$$

In [6]:
A = np.matrix([[1, -2],
               [3, 0]])
B = np.matrix([[4, -1],
               [0, 5]])
print('A + B = B + A =\n', A + B)
print('A x B =\n', np.dot(A, B))
print('B x A =\n', np.dot(B, A))

A + B = B + A =
 [[ 5 -3]
 [ 3  5]]
A x B =
 [[  4 -11]
 [ 12  -3]]
B x A =
 [[ 1 -8]
 [15  0]]


#### Задача 3
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A = \begin{pmatrix}
1 & 7 \\ 
3 & -6 
\end{pmatrix}$, $B = \begin{pmatrix}
0 & 5 \\ 
2 & -1 
\end{pmatrix}$, $C = \begin{pmatrix}
2 & -4 \\ 
1 & 1 
\end{pmatrix}$. 
##### Решение

$$3A - 2B + 4C = 3\begin{pmatrix}
1 & 7 \\ 
3 & -6 
\end{pmatrix} - 2\begin{pmatrix}
0 & 5 \\ 
2 & -1 
\end{pmatrix} + 4\begin{pmatrix}
2 & -4 \\ 
1 & 1 
\end{pmatrix} = \begin{pmatrix}
3 & 21 \\ 
9 & -18 
\end{pmatrix} + \begin{pmatrix}
0 & -10 \\ 
-4 & 2 
\end{pmatrix} + \begin{pmatrix}
8 & -16 \\ 
4 & 4 
\end{pmatrix} = \begin{pmatrix}
3-0+8 & 21-10-16 \\ 
9-4+4 & -18+2+4 
\end{pmatrix} = \begin{pmatrix}
11 & -5 \\ 
9 & -12 
\end{pmatrix}$$

In [8]:
A = np.matrix([[1, 7],
               [3, -6]])
B = np.matrix([[0, 5],
               [2, -1]])
C = np.matrix([[2, -4],
               [1, 1]])
print('3A - 2B + 4C =\n', 3*A-2*B+4*C)

3A - 2B + 4C =
 [[ 11  -5]
 [  9 -12]]


#### Задача 4
Дана матрица $A = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\
2 & 3\end{pmatrix}$. Вычислить $AA^T$ и $A^TA$.
##### Решение

$$A^T = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3\end{pmatrix}$$

$$AA^T = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\
2 & 3 
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3 \\
5\cdot4-2\cdot1 & 5\cdot5-2\cdot(-2) & 5\cdot2-2\cdot3 \\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}$$

$$A^TA = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\
2 & 3 
\end{pmatrix} = \begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3 \\
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot(-2)+3\cdot3
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}$$

In [10]:
A = np.matrix([[4, 1],
               [5, -2],
               [2, 3]])
print('A.T =\n', A.T)
print('A*A.T =\n', np.dot(A, A.T))
print('A.T*A =\n', np.dot(A.T, A))

A.T =
 [[ 4  5  2]
 [ 1 -2  3]]
A*A.T =
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T*A =
 [[45  0]
 [ 0 14]]


#### Задача 5*
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.
##### Решение

In [28]:
def vdot(a, b):
    return sum([x*y for (x,y) in zip(a, b)])


def col(i, A):
    return [x[i] for x in A]


def T(A):
    return [col(i, A) for i in range(len(A[0]))]


def mdot(A, B):
    return [[vdot(a, b) for a in A] for b in T(B)]

In [31]:
A = [[4, 1],
     [5, -2],
     [2, 3]]

print('A*A.T =')
[print(r) for r in mdot(A, T(A))]

print('A.T*A =')
[print(r) for r in mdot(T(A), A)]

'done'

A*A.T =
[17, 18, 11]
[18, 29, 4]
[11, 4, 13]
A.T*A =
[45, 0]
[0, 14]


'done'

### Часть 2

#### Задача 1
Вычислить определитель:
1. $\begin{vmatrix}
sinx & -cosx \\
cosx & sinx
\end{vmatrix}$;
2. $\begin{vmatrix}
4 & 2 & 3 \\
0 & 5 & 1 \\
0 & 0 & 9
\end{vmatrix}$; 
3. $\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix}$.
##### Решение

1. $\begin{vmatrix}
sinx & -cosx \\
cosx & sinx
\end{vmatrix} = {sin}^2x + {cos}^2x = 1$

2. 
    1. $\begin{vmatrix}
4 & 2 & 3 \\
0 & 5 & 1 \\
0 & 0 & 9
\end{vmatrix} = 4\begin{vmatrix}
5 & 1 \\
0 & 9
\end{vmatrix} - 0\begin{vmatrix}
2 & 3 \\
0 & 9
\end{vmatrix} + 0\begin{vmatrix}
2 & 3 \\
5 & 1
\end{vmatrix} = 4 \cdot 45 = 180$

    2. $\begin{vmatrix}
4 & 2 & 3 \\
0 & 5 & 1 \\
0 & 0 & 9
\end{vmatrix} = 2\begin{vmatrix}
0 & 1 \\
0 & 9
\end{vmatrix} - 5\begin{vmatrix}
4 & 3 \\
0 & 9
\end{vmatrix} + 0\begin{vmatrix}
4 & 3 \\
0 & 1
\end{vmatrix} = 5 \cdot 36 = 180$

3. $\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix} = 7\begin{vmatrix}
2 & 3 \\
5 & 6
\end{vmatrix} - 8\begin{vmatrix}
1 & 3 \\
4 & 6
\end{vmatrix} + 9\begin{vmatrix}
1 & 2 \\
4 & 5
\end{vmatrix} = 7 \cdot (12 - 15) - 8 \cdot (6 - 12) + 9 \cdot (5 - 8) = -21 + 48 - 27 = 0$

In [15]:
A = [[4, 2, 3],
     [0, 5, 1],
     [0, 0, 9]]
B = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
print(f'det(A) = {np.linalg.det(A):.0f}')
print(f'det(B) = {np.linalg.det(B):.0f}')

det(A) = 180
det(B) = -0


#### Задача 2
Определитель матрицы $A$ равен $4$. Найти:
1. $det(A^2)$;
2. $det(A^T)$;
3. $det(2A)$.
##### Решение

1. 4
2. 2
3. 4

#### Задача 3
Доказать, что матрица $\begin{pmatrix}
-2 & 7 & -3 \\
4 & -14 & 6 \\
-3 & 7 & 13
\end{pmatrix}$ вырожденная.
##### Решение

$$\begin{pmatrix}
-2 & 7 & -3 \\
4 & -14 & 6 \\
-3 & 7 & 13
\end{pmatrix} = 7\begin{pmatrix}
4 & 6 \\
-3 & 13
\end{pmatrix} + 14\begin{pmatrix}
-2 & -3 \\
-3 & 13
\end{pmatrix} + 7\begin{pmatrix}
-2 & -3 \\
4 & 6
\end{pmatrix} = 7 \cdot (52+18) + 14 \cdot (-26-9) + 7 \cdot (-12+12) = 490 - 490 = 0$$

In [16]:
A = [[-2, 7, -3],
     [4, -14, 6],
     [-3, 7, 13]]
print(f'det(A) = {np.linalg.det(A):.0f}')

det(A) = 0


#### Задача 4
Найти ранг матрицы:
1. $\begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1 \\
2 & 3 & 4
\end{pmatrix}$; 
2. $\begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 2 & 2 \\
0 & 0 & 4 & 3 \\
2 & 3 & 5 & 6
\end{pmatrix}$. 
##### Решение

1. $\begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1 \\
2 & 3 & 4
\end{pmatrix} \Rightarrow \begin{pmatrix}
1 & 2 & 3 \\
1 & 1 & 1
\end{pmatrix} \Rightarrow \begin{pmatrix}
0 & 1 & 2 \\
1 & 1 & 1
\end{pmatrix} \Rightarrow rank = 2$
2. $\begin{pmatrix}
0 & 0 & 2 & 1 \\
0 & 0 & 2 & 2 \\
0 & 0 & 4 & 3 \\
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow \begin{pmatrix}
0 & 0 & 0 & -1 \\
0 & 0 & 2 & 2 \\
0 & 0 & 0 & -1 \\
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow \begin{pmatrix}
0 & 0 & 0 & -1 \\
0 & 0 & 2 & 2 \\
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow rank = 3$

In [17]:
A = [[1, 2, 3],
     [1, 1, 1],
     [2, 3, 4]]
B = [[0, 0, 2, 1],
     [0, 0, 2, 2],
     [0, 0, 4, 3],
     [2, 3, 5, 6]]
print(f'det(A) = {np.linalg.matrix_rank(A)}')
print(f'det(B) = {np.linalg.matrix_rank(B)}')

det(A) = 2
det(B) = 3
