# Линейная алгебра
## Урок 5. Сингулярное разложение матриц

In [2]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

### Задание 1

Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

#### Решение

In [3]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3,-4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [4]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.825 0.    0.   ]
 [0.    6.141 0.   ]
 [0.    0.    2.533]
 [0.    0.    0.   ]
 [0.    0.    0.   ]]
Матрица U:
[[ 0.171  0.157 -0.531 -0.799 -0.162]
 [ 0.393 -0.529  0.613 -0.434  0.031]
 [-0.144 -0.824 -0.524  0.14   0.074]
 [ 0.888  0.061 -0.247  0.378 -0.06 ]
 [ 0.081  0.108 -0.082 -0.105  0.982]]
Матрица V:
[[ 0.071 -0.367 -0.927]
 [ 0.717  0.665 -0.208]
 [ 0.693 -0.65   0.311]]


### Задание 2

Для матрицы из предыдущего задания найти:

1. евклидову норму;  
2. норму Фробениуса.

#### Решение

In [10]:
print('1. евклидова норма =', s[0])
print('2. норма Фробениуса =', np.sqrt(np.prod(s**2)))

1. евклидова норма = 8.824868854820442
2. норма Фробениуса = 137.2479508043745
