# Линейная алгебра
## Урок 3. Линейные преобразования

In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

#### Задача 1

Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей
$$A=\begin{pmatrix}
-1 & -6 \\
2  &  6
\end{pmatrix}.$$

##### Решение

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6 \\
2 & 6 - \lambda
\end{vmatrix} = 0$$

$$(-1 - \lambda)\cdot(6 - \lambda) - 2\cdot(-6) = 0$$

$$-6 + \lambda - 6\lambda + {\lambda}^2 + 12 = 0$$

$${\lambda}^2 - 5\lambda + 6 = 0$$

Найдём корни квадратного уравнения по теореме Виета:

$$\begin{cases}
{\lambda}_1 + {\lambda}_2 = 5,
\\
{\lambda}_1 \cdot {\lambda}_2 = 6.
\end{cases}$$

$${\lambda}_1 = 2; {\lambda}_2 = 3.$$

Теперь найдем собственные векторы вида $\begin{pmatrix}x_1 \\ x_2\end{pmatrix}$, подставив полученное собственное значение в выражение $Ax=\lambda x$:

$$\begin{pmatrix}
-1 & -6 \\
2  &  6
\end{pmatrix} \begin{pmatrix}
x_1 \\ 
x_2
\end{pmatrix} = \lambda \begin{pmatrix}
x_1 \\ 
x_2
\end{pmatrix}.$$

Для ${\lambda}_1$ получим:

$$\begin{cases}
-1x_1 - 6x_2 = 2x_1,
\\
2x_1 + 6x_2 = 2x_2.
\end{cases}$$

$$\begin{cases}
3x_1 + 6x_2 = 0,
\\
2x_1 + 4x_2 = 0.
\end{cases}$$

$$x_1 = -2x_2$$

$$x = \begin{pmatrix}1 \\ -0.5\end{pmatrix}$$

In [3]:
A = np.array([
    [-1, -6], 
    [2, 6]
])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.894  0.832]
 [ 0.447 -0.555]]


#### Задача 2

Дан оператор поворота на $180$ градусов, задаваемый матрицей
$$A=\begin{pmatrix}
-1 &  0 \\
0  & -1
\end{pmatrix}.$$
Показать, что **любой** вектор является для него собственным.

##### Решение

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & 0 \\
0 & -1-\lambda
\end{vmatrix} = 0$$

$$(-1 - \lambda)^2 - 0\cdot0 = 0$$

$${\lambda}^2 + 2\lambda + 1 = 0$$

Найдём корни квадратного уравнения по теореме Виета:

$$\begin{cases}
{\lambda}_1 + {\lambda}_2 = -2,
\\
{\lambda}_1 \cdot {\lambda}_2 = 1.
\end{cases}$$

$${\lambda}_1 = {\lambda}_2 = -1.$$

Теперь найдем собственные векторы вида $\begin{pmatrix}x_1 \\ x_2\end{pmatrix}$, подставив полученное собственное значение в выражение $Ax=\lambda x$:

$$\begin{pmatrix}
-1 & 0 \\
0  & -1
\end{pmatrix} \begin{pmatrix}
x_1 \\ 
x_2
\end{pmatrix} = \lambda \begin{pmatrix}
x_1 \\ 
x_2
\end{pmatrix}.$$

Получим:

$$\begin{cases}
-x_1 + 0x_2 = -x_1,
\\
0x_1 + -x_2 = -x_2.
\end{cases}$$

$$\begin{cases}
x_1 = x_1,
\\
x_2 = x_2.
\end{cases}$$

Отсюда можно сделать вывод, что любые не нулевые значения $x_1$ и $x_2$ можно подставить в координаты собственного вектора данного оператора.

In [4]:
A = np.array([
    [-1, 0], 
    [0, -1]
])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


#### Задача 3

Пусть линейный оператор задан матрицей
$$A=\begin{pmatrix}
1 & 1 \\
-1 & 3
\end{pmatrix}$$
Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

##### Решение 1

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором
$$\begin{pmatrix}
1 & 1 \\
-1 & 3
\end{pmatrix} \begin{pmatrix}
1 \\
1
\end{pmatrix} = \lambda\begin{pmatrix}
1 \\
1
\end{pmatrix}.$$

Из этого будет следовать, что

$$\begin{cases}
1 + 1 = \lambda,
\\
-1 + 3 = \lambda.
\end{cases} \Rightarrow \lambda = 2$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2$. 

##### Решение 2

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
1-\lambda & 1 \\
-1 & 3 - \lambda
\end{vmatrix} = 0$$

$$(1 - \lambda)\cdot(3 - \lambda) - 1\cdot(-1) = 0$$

$$3 - \lambda - 3\lambda + {\lambda}^2 + 1 = 0$$

$${\lambda}^2 - 4\lambda + 4 = 0$$

Найдём корни квадратного уравнения по теореме Виета:

$$\begin{cases}
{\lambda}_1 + {\lambda}_2 = 4,
\\
{\lambda}_1 \cdot {\lambda}_2 = 4.
\end{cases}$$

$${\lambda}_1 = {\lambda}_2 = 2.$$

Теперь найдем собственные векторы вида $\begin{pmatrix}x_1 \\ x_2\end{pmatrix}$, подставив полученное собственное значение в выражение $Ax=\lambda x$:

$$\begin{pmatrix}
1 & 1 \\
-1 & 3
\end{pmatrix} \begin{pmatrix}
x_1 \\ 
x_2
\end{pmatrix} = \lambda \begin{pmatrix}
x_1 \\ 
x_2
\end{pmatrix}.$$

Получим:

$$\begin{cases}
x_1 + x_2 = 2x_1,
\\
-x_1 + 3x_2 = 2x_2.
\end{cases}$$

$$x_1 = x_2$$

Отсюда можно сделать вывод, что вектор $x=(1,1)$ будет являться собственным вектором этого линейного оператора.

In [5]:
A = np.array([
    [1, 1], 
    [-1, 3]
])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.707 -0.707]
 [ 0.707 -0.707]]


#### Задача 4

Пусть линейный оператор задан матрицей
$$A=\begin{pmatrix}
0 & 3 & 0 \\
3 & 0 & 0 \\
0 & 0 & 3
\end{pmatrix}.$$
Установить, является ли вектор $x=(3,-3,-4)$ собственным вектором этого линейного оператора.

##### Решение

##### Решение 1

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором
$$\begin{pmatrix}
0 & 3 & 0 \\
3 & 0 & 0 \\
0 & 0 & 3
\end{pmatrix} \begin{pmatrix}
3 \\
-3 \\
-4
\end{pmatrix} = \lambda\begin{pmatrix}
3 \\
-3 \\
-4
\end{pmatrix}.$$

Из этого будет следовать, что

$$\begin{cases}
0\cdot3 + 3\cdot(-3) + 0\cdot(-4) = 3\lambda,
\\
3\cdot3 + 0\cdot(-3) + 0\cdot(-4) = -3\lambda,
\\
0\cdot3 + 0\cdot(-3) + 3\cdot(-4) = -4\lambda.
\end{cases} \Rightarrow \begin{cases}
\lambda = -3,
\\
\lambda = -3,
\\
\lambda = 3.
\end{cases} \Rightarrow \lambda = 2$$

Такая система не имеет смысла, следовательно, вектор $x=(3,-3,-4)$ не является собственным вектором линейного оператора, заданного матрицей $A$. 

##### Решение 2

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-\lambda & 3 & 0 \\
3 & -\lambda & 0 \\
0 & 0 & 3-\lambda
\end{vmatrix} = 0$$

$$0\begin{vmatrix}
-\lambda & 0 \\
0 & 3-\lambda
\end{vmatrix} - 3\begin{vmatrix}
3 & 0 \\
0 & 3-\lambda
\end{vmatrix} + 0\begin{vmatrix}
3 & 0 \\
-\lambda & 0
\end{vmatrix} = 0$$

$$-3(9 - 3\lambda) = 0$$

$$9\lambda = -27$$

$$\lambda = -3$$

Теперь найдем собственны вектора вида $\begin{pmatrix}x_1 \\ x_2 \\ x_3\end{pmatrix}$, подставив полученное собственное значение в выражение $Ax=\lambda x$:

$$\begin{pmatrix}
0 & 3 & 0 \\
3 & 0 & 0 \\
0 & 0 & 3
\end{pmatrix} \begin{pmatrix}
x_1 \\ 
x_2 \\
x_3
\end{pmatrix} = \lambda \begin{pmatrix}
x_1 \\ 
x_2 \\
x_3
\end{pmatrix}.$$

Получим:

$$\begin{cases}
0x_1 + 3x_2 + 0x_3 = -3x_1,
\\
3x_1 + 0x_2 + 0x_3 = -3x_2,
\\
0x_1 + 0x_2 + 3x_3 = -3x_3.
\end{cases}$$

$$\begin{cases}
x_2 = -x_1,
\\
x_1 = -x_2,
\\
x_3 = -x_3.
\end{cases}$$

В данных условиях вектор $x=(3,-3,-4)$ не является собственным вектором линейного оператора, заданного матрицей $A$. 

In [6]:
A = np.array([
    [0, 3, 0], 
    [3, 0, 0],
    [0, 0, 3]
])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.707 -0.707  0.   ]
 [ 0.707  0.707  0.   ]
 [ 0.     0.     1.   ]]
