# СЛАУ

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

### Задание 1
Решить линейную систему

In [4]:
A = np.array([[1, 2, 3],
              [4, 0, 6],
              [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

### Задание 2
Найти псевдорешение

In [7]:
A = np.array([[1, 2, -1],
              [3, -4, 0],
              [8, -5, 2],
              [2, 0, -5],
              [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond=None)[0]

array([ 1.13919353, -0.90498444, -0.9009803 ])

In [8]:
np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ]) - B

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])

### Задание 3
Сколько решений имеет линейная система

In [21]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 3)

Ранг матрицы A меньше ранга расширенной матрицы C, следовательно система не имеет решений

In [26]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[3, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
print("Rank", np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001))
np.linalg.solve(A, B.T)

Rank 2 2


array([[ 0.33333333],
       [-4.66666667],
       [ 4.        ]])

### Задание 4
Вычислить LU-разложение матрицы

In [34]:
A = np.array([[1, 2, 3],
              [2, 16, 21],
              [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

In [40]:
B = np.array([9, 150, 1])
np.linalg.solve(A, B)

array([-9.45833333, 19.85416667, -7.08333333])

### Задание 5
Найти нормальное псевдорешение недоопределенной системы, определив функцию Q(x, y, z), равную норме решения, и найдя её минимум.

In [49]:
def Q(x, y, z):
    return x**2 + y**2 + z**2

In [50]:
A = np.array([[1, 2, -1],
              [8, -5, 2]])
B = np.array([1, 12])

In [51]:
np.linalg.lstsq(A, B, rcond=None)[0]

array([ 1.38191882, -0.18081181,  0.0202952 ])

### Задание 6
Найти одно из псевдорешений вырожденной системы.

In [62]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

R1 = R[:2, :2]
B1 = np.dot(np.transpose(Q), B)[:2]

X1 = np.linalg.solve(R1, B1)

X = np.append(X1, 0)
np.linalg.norm(X)

1.4999999999999893